name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v3
      - name: Build release
        run: swift build -c release --product fx-upscale
      - name: Test
        run: swift test
      - name: Build with Xcode
        run: xcodebuild build -scheme Upscaling -destination "platform=macOS"
